name: Feature Request
description: Suggest a new feature for Treeship
labels: ["enhancement"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this affect?
      options:
        - CLI (@treeship/cli)
        - Python SDK (treeship-sdk)
        - JavaScript SDK (@treeship/sdk)
        - Sidecar (Docker)
        - Protocol
        - New Integration
        - Documentation
        - Other
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve? What's the use case?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?
