#!/usr/bin/env python3
"""Generate the capability map from source. Nothing here is hand-maintained.

`docs/feature-inventory.yml` is curated: a human decides which features exist
and what they mean. This is the complement -- a mechanical inventory of every
surface a consumer can actually reach, derived only from the code:

    CLI commands      packages/cli/src        (clap subcommand registrations)
    Hub routes        packages/hub            (chi route registrations)
    Wire types        packages/core/src       (types deriving Serialize)

Curation and derivation answer different questions. The inventory says "what do
we ship, and is it stable." This says "what is actually there, right now, to the
byte." Drift between them is the interesting signal, so `--check` reports it.

# Why "derives Serialize" is the right cut for types

`packages/core/src` has 172 public structs and enums. Most are internal:
public because Rust needs cross-module visibility, not because anyone outside
programs against them. Listing all 172 would bury the ~100 that matter.

A type that derives `Serialize` crosses a process boundary. It appears in a
signed artifact, an API response, or a config file -- so renaming a field is a
breaking change for somebody, whether or not we meant it to be. That makes
serializability a mechanical, judgment-free definition of the public surface,
and it is why this can be generated rather than argued about.

Usage:
    python3 scripts/gen-capability-map.py            # write the map
    python3 scripts/gen-capability-map.py --check    # fail if stale
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "capability-map.json"

HUB = ROOT / "packages" / "hub"
CORE = ROOT / "packages" / "core" / "src"
CLI = ROOT / "packages" / "cli" / "src"

ROUTE_RE = re.compile(r'\.(Get|Post|Put|Patch|Delete|Handle)\(\s*"(/v1/[^"]*)"')

# A derive block, then any further attributes, then the item. Attributes
# between the derive and the item (`#[serde(...)]`, docs) are common and must
# not break the match.
SERDE_RE = re.compile(
    r"#\[derive\([^)]*Serialize[^)]*\)\]\s*(?:#\[[^\]]*\]\s*)*"
    r"pub\s+(struct|enum)\s+([A-Z]\w+)"
)


def hub_routes() -> list[dict]:
    """Every /v1 route registered in the Go source, with its verbs."""
    found: dict[str, set[str]] = {}
    if not HUB.is_dir():
        return []
    for go in HUB.rglob("*.go"):
        if go.name.endswith("_test.go"):
            continue
        for verb, path in ROUTE_RE.findall(go.read_text(encoding="utf-8", errors="replace")):
            found.setdefault(path, set()).add(verb.upper())
    return [
        {"path": p, "methods": sorted(v)}
        for p, v in sorted(found.items())
    ]


def wire_types() -> list[dict]:
    """Types that cross a process boundary, with the module that owns them."""
    out: list[dict] = []
    if not CORE.is_dir():
        return out
    for rs in sorted(CORE.rglob("*.rs")):
        text = rs.read_text(encoding="utf-8", errors="replace")
        rel = rs.relative_to(ROOT).as_posix()
        for kind, name in SERDE_RE.findall(text):
            out.append({"name": name, "kind": kind, "source": rel})
    out.sort(key=lambda t: t["name"])
    return out


def cli_commands() -> list[str]:
    """Top-level subcommands, read from the built binary when available.

    The binary is the truth -- parsing clap attributes out of source misses
    conditionally-registered commands and feature-gated ones. Falls back to an
    empty list rather than guessing, so a missing binary shows up as "not
    measured" instead of a confidently wrong zero.
    """
    binary = ROOT / "target" / "debug" / "treeship"
    if not binary.exists():
        return []
    try:
        out = subprocess.run(
            [str(binary), "--help"], capture_output=True, text=True, timeout=30
        ).stdout
    except (OSError, subprocess.SubprocessError):
        return []
    skip = {"help"}
    return sorted(
        c for c in re.findall(r"^  ([a-z][a-z-]+)\s{2,}", out, re.M) if c not in skip
    )


def build() -> dict:
    routes = hub_routes()
    types = wire_types()
    cli = cli_commands()
    return {
        "$comment": (
            "GENERATED by scripts/gen-capability-map.py -- do not edit. "
            "Mechanical inventory of every reachable surface, derived from "
            "source. For what each feature MEANS and how stable it is, see "
            "docs/feature-inventory.yml."
        ),
        "counts": {
            "cli_commands": len(cli),
            "hub_routes": len(routes),
            "wire_types": len(types),
        },
        "cli_commands": cli,
        "hub_routes": routes,
        "wire_types": types,
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the map is stale")
    args = ap.parse_args()

    current = build()
    rendered = json.dumps(current, indent=2) + "\n"

    if args.check:
        if not OUT.exists():
            print(f"  err   {OUT.relative_to(ROOT)} missing -- run gen-capability-map.py")
            return 1
        if OUT.read_text() != rendered:
            print(f"  err   {OUT.relative_to(ROOT)} is stale")
            # Say WHAT drifted. "regenerate it" without naming the delta means
            # a reviewer cannot tell an intended API change from an accident.
            try:
                old = json.loads(OUT.read_text())
            except json.JSONDecodeError:
                old = {}
            for key, label in (
                ("cli_commands", "CLI command"),
                ("hub_routes", "hub route"),
                ("wire_types", "wire type"),
            ):
                def ident(x):
                    return x if isinstance(x, str) else (x.get("path") or x.get("name"))

                before = {ident(x) for x in old.get(key, [])}
                after = {ident(x) for x in current.get(key, [])}
                for added in sorted(after - before):
                    print(f"        + {label} {added}")
                for gone in sorted(before - after):
                    print(f"        - {label} {gone}")
            print()
            print("  Run: python3 scripts/gen-capability-map.py")
            return 1
        c = current["counts"]
        print(
            f"  ✓ capability map current "
            f"({c['cli_commands']} commands, {c['hub_routes']} routes, "
            f"{c['wire_types']} wire types)"
        )
        return 0

    OUT.write_text(rendered)
    c = current["counts"]
    print(f"  ✓ wrote {OUT.relative_to(ROOT)}")
    print(
        f"    {c['cli_commands']} CLI commands, {c['hub_routes']} hub routes, "
        f"{c['wire_types']} wire types"
    )
    if c["cli_commands"] == 0:
        print("    note: no CLI commands found -- build the binary first "
              "(cargo build --bin treeship)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
