#!/usr/bin/env python3
"""Generate docs/content/docs/integrations/index.mdx.

`integrations/agents.json` names its own consumers, and one of them --
"treeship.dev/integrations docs page" -- never existed. The other three do.
So the ecosystem had a source of truth and no page rendering it, which is how
a shipping partner integration (Perplexity Computer, `partner_shipping`) and a
shipping plugin (Kimi Code) stayed invisible.

Two halves, on purpose:

  Harnesses      derived from integrations/agents.json -- ids, vendors, install
                 commands, and per-tier availability.
  Everything else discovered from the .mdx files in this directory, using their
                 own frontmatter. A page cannot be listed here unless it exists,
                 and cannot exist here unless it is categorized below.

That second rule is the point. A new integration page with no category fails
this script rather than quietly missing from the index.

Usage:  gen-integrations-index.py [--check]
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
AGENTS = ROOT / "integrations" / "agents.json"
PAGES = ROOT / "docs" / "content" / "docs" / "integrations"
OUT = PAGES / "index.mdx"

# Every non-harness page must appear here. Adding a page without categorizing
# it is a failure, not a silent omission.
CATEGORIES: dict[str, tuple[str, str]] = {
    "mcp": ("Protocol bridges", "Speak a protocol, get receipts."),
    "a2a": ("Protocol bridges", ""),
    "agent-skills": ("Skills", "One skill file, any agent that reads skills."),
    "install": ("Skills", ""),
    "langchain": ("Frameworks", "Wrap a framework's calls."),
    "memory-proofs": ("Sibling products", "Other Zerker systems that emit or consume Treeship evidence."),
    "zerker-reason": ("Sibling products", ""),
    "ninjatech": ("Partners and applied work", "Shipped elsewhere, verifiable here."),
    "lobster-cash": ("Partners and applied work", ""),
    "robinhood-agentic-trading": ("Partners and applied work", ""),
    "verifiable-intent": ("Partners and applied work", ""),
}

ORDER = ["Protocol bridges", "Skills", "Frameworks", "Sibling products", "Partners and applied work"]

FRONTMATTER = re.compile(r"^---\s*\n(.*?)\n---", re.S)


def frontmatter(path: pathlib.Path) -> dict[str, str]:
    m = FRONTMATTER.match(path.read_text())
    if not m:
        return {}
    out: dict[str, str] = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def tier(agent: dict, name: str) -> str:
    """Render one availability cell without inventing a state for a missing key."""
    block = agent.get(name)
    if not isinstance(block, dict):
        return "--"
    if block.get("available") is True:
        return "yes"
    if block.get("available") is False:
        return "no"
    return "--"


def build() -> str:
    data = json.loads(AGENTS.read_text())
    agents = data["agents"]
    track = data.get("partnership_track", [])

    lines = [
        "---",
        "title: Integrations",
        "description: Every runtime, protocol, product, and partner that emits or verifies Treeship evidence.",
        "---",
        "",
        "{/* GENERATED by scripts/gen-integrations-index.py -- do not edit.",
        "    Harness rows come from integrations/agents.json; every other row is",
        "    discovered from the pages in this directory. */}",
        "",
        "A receipt is the same bytes wherever it was produced. That is the point of this",
        "list: an agent running under one of these verifies against the same roots as an",
        "agent running under any other, with no registry in the loop.",
        "",
        "## Agent harnesses",
        "",
        "Where an agent actually runs. `treeship add <id>` installs the skill.",
        "",
        "| Agent | Vendor | Actor URI | Skill | Plugin | Install |",
        "|---|---|---|---|---|---|",
    ]
    undocumented: list[str] = []
    for a in sorted(agents, key=lambda x: x["id"]):
        skill = a.get("skill") or {}
        install = skill.get("install") or f"treeship add {a['id']}"
        if (PAGES / f"{a['id']}.mdx").exists():
            name = f"[{a['display_name']}](./{a['id']})"
        else:
            # Ships, but has no page yet. Say so in the table rather than
            # linking into a 404 or dropping the row.
            name = f"{a['display_name']} <sup>no page yet</sup>"
            undocumented.append(a["id"])
        lines.append(
            f"| {name} | {a.get('vendor','--')} | "
            f"`{a.get('actor_uri','--')}` | {tier(a,'skill')} | {tier(a,'plugin')} | `{install}` |"
        )
    if undocumented:
        print(
            "  note  ships but has no docs page: " + ", ".join(undocumented),
            file=sys.stderr,
        )

    agent_ids = {a["id"] for a in agents}
    by_cat: dict[str, list[tuple[str, str, str]]] = {}
    uncategorized: list[str] = []
    for page in sorted(PAGES.glob("*.mdx")):
        slug = page.stem
        # Harness pages are already rendered by the table above.
        if slug == "index" or slug in agent_ids:
            continue
        cat = CATEGORIES.get(slug)
        if cat is None:
            uncategorized.append(slug)
            continue
        fm = frontmatter(page)
        by_cat.setdefault(cat[0], []).append(
            (slug, fm.get("title", slug), fm.get("description", ""))
        )

    if uncategorized:
        raise SystemExit(
            "  err   these integration pages are not categorized in "
            "scripts/gen-integrations-index.py:\n"
            + "".join(f"        + {s}\n" for s in uncategorized)
            + "\n  A page that is not categorized would be missing from the index "
            "silently, which is the failure this generator exists to prevent."
        )

    blurbs = {v[0]: v[1] for v in CATEGORIES.values() if v[1]}
    for cat in ORDER:
        rows = by_cat.get(cat)
        if not rows:
            continue
        lines += ["", f"## {cat}", ""]
        if blurbs.get(cat):
            lines += [blurbs[cat], ""]
        lines += ["| Integration | What it is |", "|---|---|"]
        for slug, title, desc in rows:
            lines.append(f"| [{title}](./{slug}) | {desc} |")

    if track:
        lines += [
            "",
            "## Partnership track",
            "",
            "Runtimes we have assessed but do not ship an integration for yet. Status is",
            "stated rather than implied: `no_public_surface` means the runtime exposes no",
            "hook we could attach to, not that we have not tried.",
            "",
            "| Runtime | Vendor | Status | Notes |",
            "|---|---|---|---|",
        ]
        for e in sorted(track, key=lambda x: x.get("id", "")):
            note = (e.get("notes") or "").replace("|", "\\|")
            lines.append(
                f"| {e.get('display_name', e.get('id'))} | {e.get('vendor','--')} | "
                f"`{e.get('status','--')}` | {note} |"
            )

    lines += [
        "",
        "## Adding one",
        "",
        "Edit `integrations/agents.json` for a harness, or add a page to this directory",
        "and categorize it in `scripts/gen-integrations-index.py`. Then regenerate:",
        "",
        "```bash",
        "python3 scripts/gen-integrations-index.py",
        "```",
        "",
        "CI runs it with `--check`, so this page cannot drift from what ships.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    want = build()
    check = "--check" in sys.argv
    have = OUT.read_text() if OUT.exists() else None
    if check:
        if have != want:
            print("  err   docs/content/docs/integrations/index.mdx is stale")
            print("\n  Run: python3 scripts/gen-integrations-index.py")
            return 1
        print("  ✓ integrations index current")
        return 0
    OUT.write_text(want)
    print(f"  ✓ wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
