#!/usr/bin/env bash
# Treeship bootstrap for a Grok Bot cloud VM.
#
# The Bot runs this, not the human. It is idempotent by design: the Grok docs
# say to "treat temporary directories, manually installed packages, and
# uncommitted application state as replaceable," so the binary WILL disappear.
# Re-running must restore the same identity, never mint a second one.
#
# Two things live in different places on purpose:
#   /workspace/treeship        durable: config, keystore, envelopes, the shim
#   /workspace/treeship/bin    replaceable: the binary itself
#
# Why the shim: the CLI resolves its ship as
#   --config -> TREESHIP_CONFIG -> .treeship/config.json walking up from cwd
#   -> ~/.treeship/config.json
# `TREESHIP_HOME` does NOT move the ship (it is the rig ledger's variable), and
# TREESHIP_CONFIG alone leaves checkpoints in ~/.treeship/merkle/checkpoints,
# which is not durable here. The shim pins both HOME and TREESHIP_CONFIG so a
# bare `treeship ...` typed by the Bot cannot silently adopt whatever ship the
# cwd walk happens to find.
set -euo pipefail

TS_ROOT="${TREESHIP_ROOT:-/workspace/treeship}"
TS_HOME="$TS_ROOT/home"
TS_BIN="$TS_ROOT/bin"
ACTOR_NAME="${TREESHIP_ACTOR_NAME:-grok}"

mkdir -p "$TS_BIN" "$TS_HOME" "$TS_ROOT/inbox" "$TS_ROOT/outbox" "$TS_ROOT/presentations"

# 1. Binary — reinstall only when missing.
if [ ! -x "$TS_BIN/treeship" ]; then
  if command -v treeship >/dev/null 2>&1; then
    ln -sf "$(command -v treeship)" "$TS_BIN/treeship"
  else
    echo "installing treeship..."
    curl -fsSL treeship.dev/install | sh >/dev/null
    command -v treeship >/dev/null 2>&1 || { echo "install failed: treeship not on PATH" >&2; exit 1; }
    ln -sf "$(command -v treeship)" "$TS_BIN/treeship"
  fi
fi

# 2. Shim — every invocation is scoped, whatever the Bot types.
cat > "$TS_ROOT/ts" <<SHIM
#!/usr/bin/env bash
# Generated by bootstrap.sh. Pins this account's ship for every call.
exec env HOME="$TS_HOME" TREESHIP_CONFIG="$TS_ROOT/config.json" "$TS_BIN/treeship" "\$@"
SHIM
chmod +x "$TS_ROOT/ts"

# 3. Ship — init only when there is no config. This is the line that keeps the
#    identity stable across a package wipe.
if [ ! -f "$TS_ROOT/config.json" ]; then
  "$TS_ROOT/ts" init --quiet >/dev/null
  echo "initialized a new ship at $TS_ROOT/config.json"
else
  echo "existing ship kept at $TS_ROOT/config.json"
fi

# 4. Agent — `onboard` is idempotent and safe on every boot. It needs a bare
#    name plus a capability source; `--own-key` belongs to `agent register`.
"$TS_ROOT/ts" onboard "$ACTOR_NAME" --tools "a2a.*,treeship.*" --format json >/dev/null
"$TS_ROOT/ts" checkpoint --format json >/dev/null

echo
echo "ready. Use $TS_ROOT/ts for every Treeship command."
"$TS_ROOT/ts" keys export 2>/dev/null | grep -E 'trust add .* --kind cert_issuer' | head -1 \
  | sed 's/^ */  give a peer this line to pin you: /' || true
