use serde::{Deserialize, Serialize};
use std::path::PathBuf;

use treeship_zk_risc0_methods::TREESHIP_CHAIN_VERIFIER_ELF;
use treeship_zk_risc0_methods::TREESHIP_CHAIN_VERIFIER_ID;

/// Result of a RISC Zero chain proof.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChainProofResult {
    pub image_id: String,
    pub chain_root_id: Option<String>,
    pub chain_tip_id: Option<String>,
    pub artifact_count: usize,
    pub chain_intact: bool,
    pub all_digests_valid: bool,
    pub proved_at: String,
    pub prover_mode: String,
    /// Serialized RISC Zero receipt for offline verification.
    pub receipt_bytes: Vec<u8>,
}

/// Proving mode.
#[derive(Debug, Clone, Copy)]
pub enum ProverMode {
    Local,
}

impl Default for ProverMode {
    fn default() -> Self {
        ProverMode::Local
    }
}

/// A minimal artifact for passing to the guest program.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChainArtifact {
    pub artifact_id: String,
    pub digest: String,
    pub payload_type: String,
    pub signed_at: String,
    pub parent_id: Option<String>,
    pub signature: String,
    pub pae_message: Vec<u8>,
}

/// Minimal artifact for the guest (matches guest's ChainArtifact).
#[derive(Debug, Clone, Serialize, Deserialize)]
struct GuestArtifact {
    artifact_id: String,
    digest: String,
    parent_id: Option<String>,
}

/// Guest output (matches guest's ChainProofOutput).
#[derive(Debug, Clone, Serialize, Deserialize)]
struct GuestOutput {
    artifact_count: usize,
    chain_intact: bool,
    all_digests_valid: bool,
}

/// RISC Zero chain prover.
pub struct RiscZeroProver {
    mode: ProverMode,
}

impl RiscZeroProver {
    pub fn new(mode: ProverMode) -> Self {
        Self { mode }
    }

    pub fn from_env() -> Self {
        if let Ok(key) = std::env::var("BONSAI_API_KEY") {
            if !key.is_empty() {
                eprintln!(
                    "[treeship] BONSAI_API_KEY detected but Bonsai integration \
                     is coming in v0.6.0. Using local prover."
                );
            }
        }
        Self { mode: ProverMode::Local }
    }

    /// Prove a chain of artifacts using the RISC Zero zkVM.
    /// Slow (~5-15 min on CPU). Always call from a background thread.
    pub fn prove_chain(
        &self,
        artifacts: &[ChainArtifact],
        _public_key_bytes: [u8; 32],
    ) -> Result<ChainProofResult, Box<dyn std::error::Error>> {
        eprintln!(
            "[treeship] proving chain of {} artifacts locally...",
            artifacts.len()
        );

        let guest_artifacts: Vec<GuestArtifact> = artifacts.iter().map(|a| GuestArtifact {
            artifact_id: a.artifact_id.clone(),
            digest: a.digest.clone(),
            parent_id: a.parent_id.clone(),
        }).collect();

        let env = risc0_zkvm::ExecutorEnv::builder()
            .write(&guest_artifacts)?
            .build()?;

        let receipt = risc0_zkvm::default_prover()
            .prove(env, TREESHIP_CHAIN_VERIFIER_ELF)?
            .receipt;

        receipt.verify(TREESHIP_CHAIN_VERIFIER_ID)?;

        let output: GuestOutput = receipt.journal.decode()?;
        let receipt_bytes = bincode::serialize(&receipt)?;

        let now = {
            use std::time::{SystemTime, UNIX_EPOCH};
            let secs = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs();
            format!("{}Z", secs)
        };

        let image_id = hex::encode(
            TREESHIP_CHAIN_VERIFIER_ID.iter()
                .flat_map(|w| w.to_le_bytes())
                .collect::<Vec<u8>>()
        );

        eprintln!("[treeship] chain proof complete. image_id: {}", &image_id[..16]);

        Ok(ChainProofResult {
            image_id,
            chain_root_id: artifacts.first().map(|a| a.artifact_id.clone()),
            chain_tip_id: artifacts.last().map(|a| a.artifact_id.clone()),
            artifact_count: output.artifact_count,
            chain_intact: output.chain_intact,
            all_digests_valid: output.all_digests_valid,
            proved_at: now,
            prover_mode: format!("{:?}", self.mode),
            receipt_bytes,
        })
    }

    /// Verify a chain proof receipt offline.
    pub fn verify(proof: &ChainProofResult) -> Result<bool, Box<dyn std::error::Error>> {
        if proof.receipt_bytes.is_empty() {
            return Err("empty receipt -- proof was not generated by the zkVM".into());
        }

        let receipt: risc0_zkvm::Receipt = bincode::deserialize(&proof.receipt_bytes)?;
        receipt.verify(TREESHIP_CHAIN_VERIFIER_ID)?;

        let output: GuestOutput = receipt.journal.decode()?;
        Ok(output.chain_intact && output.all_digests_valid)
    }

    pub fn save_proof(proof: &ChainProofResult, path: &PathBuf) -> Result<(), Box<dyn std::error::Error>> {
        let json = serde_json::to_vec_pretty(proof)?;
        std::fs::write(path, json)?;
        Ok(())
    }

    pub fn load_proof(path: &PathBuf) -> Result<ChainProofResult, Box<dyn std::error::Error>> {
        let bytes = std::fs::read(path)?;
        let proof: ChainProofResult = serde_json::from_slice(&bytes)?;
        Ok(proof)
    }
}
